### ISSUE TITLE
Deposits on ETH open channels for 0 amounts

### ISSUE THREAD

**Issue by karzak** [Kava-Labs/switch-api#7]
Maybe 10% of the time when I deposit on ETH, I get the following error:

```uplinks.store.ts?339d:97 deposit Error -> TimeoutErrorImpl {message: "Timeout has occurred", name: "TimeoutError"}```

I'm also seeing a lot of logs that look like this on the test connector for ETH

```
Feb 22 17:50:23 test-ilp-kava-io ilp-connector-error.log   connector:ilp-plugin-ethereum[eth]:info Successfully deposited 0 eth to channel 0xe5dc1f2a7b2dbb8ecae4cda53f443acce6e382481822cfb5097609ea180f4f04 +17s
Feb 22 17:50:23 test-ilp-kava-io ilp-connector-error.log   connector:ilp-plugin-ethereum[eth]:debug Depositing 0 eth to channel for fee of 0.000035679 eth +96ms
```

Which seems like it's either logging the amount wrong, or not putting any ETH in the channel.

**Comment by kincaidoneil** [comment]
Fixed by interledgerjs/ilp-plugin-ethereum@39c1c48e31a33497d73c20909e6a0ff0ce7c6e3e.
